package entity

// This code is generated by go generate.
// DO NOT EDIT BY HAND!

type {{.Name}} struct {
    {{- range $jsonName, $val := .Fields}}
        {{(Title $jsonName)}} {{(TypeOf $val) -}} `json:"{{$jsonName}}" bson:"{{$jsonName}}"`
    {{ end }}
}